In [21]:
import numpy as np
l1=[10,20,30,40,50,60]
print(l1,type(l1))
a=np.array(l1)
print(a,type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)
z=a.reshape(3,2)
print(z)

# tuple 
t=(10,20,30,40,50,60,70)
print(t,type(t))
b=np.array(t)
print(b,type(b))
print(b.dtype)
print(b.ndim)
print(b.shape)
print(b.size)
# dictionary
d1={10:1.2,20:4.5,30:6.7}
c=np.array(d1)
print(c,type(c))
print(c.dtype)
print(c.ndim)
print(c.shape)
print(c.size)


[10, 20, 30, 40, 50, 60] <class 'list'>
[10 20 30 40 50 60] <class 'numpy.ndarray'>
int32
1
(6,)
6
[[10 20]
 [30 40]
 [50 60]]
(10, 20, 30, 40, 50, 60, 70) <class 'tuple'>
[10 20 30 40 50 60 70] <class 'numpy.ndarray'>
int32
1
(7,)
7
{10: 1.2, 20: 4.5, 30: 6.7} <class 'numpy.ndarray'>
object
0
()
1


In [28]:
t1=( ((10,20,15),(30,40,25)),( (50,60,18),(70,80,35) ))
print(t1,type(t1))
a=np.array(t1)
print(a)
a.ndim
a.shape
b=a.reshape(4,3)

(((10, 20, 15), (30, 40, 25)), ((50, 60, 18), (70, 80, 35))) <class 'tuple'>
[[[10 20 15]
  [30 40 25]]

 [[50 60 18]
  [70 80 35]]]
