In [21]:
import numpy as np
import sys
lst=[10,20,30,40,50,60]
print(lst,type(lst))
print("Memory space of List object=",sys.getsizeof(lst))



[10, 20, 30, 40, 50, 60] <class 'list'>
Memory space of List object= 104


In [11]:
a=np.array(lst)
print(a,type(a))
print("Memory space of List object=",sys.getsizeof(a))

[10 20 30 40 50 60 70] <class 'numpy.ndarray'>
Memory space of List object= 140


In [14]:
#vector based operarations
a=a+2
print(a)

[16 26 36 46 56 66 76]


In [15]:
#printing dimension
print("Dimension of ndarray=",a.ndim)


Dimension of ndarray= 1


In [22]:
a.reshape(3,2)

ValueError: cannot reshape array of size 7 into shape (3,2)

In [23]:
lst=[10,20,30,40,50,60]
a=np.array(lst)
print("Dimension of ndarray=",a.ndim)
print("Dimension of ndarray=",a.ndim)
a.reshape(3,2)

Dimension of ndarray= 1


array([[10, 20],
       [30, 40],
       [50, 60]])

In [26]:
lst=[10,20,30,40,50,60,70,80,90,25,35,45]
a=np.array(lst)
print("Dimension of ndarray=",a.ndim)
a.reshape(4,3)

Dimension of ndarray= 1


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [25, 35, 45]])

In [25]:
a.reshape(4,3)

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 25, 35, 45]])

In [27]:
a.reshape(4,3).ndim

2

In [ ]:
import numpy as np
a=10
b=np.array(a)
print(b)
print(b.dtype)
print(b.ndim)
print(b.shape)
print(b.size)
print("************************")
c=2.5
d=np.array(c)
print(d)
print(d.dtype)
print(d.ndim)
print(d.shape)
print(d.size)
print("*****************************************")
# range
r=range(12)
rd=np.array(r)
print(rd)
print(rd.dtype)
print(rd.ndim)
print(rd.shape)
print(rd.size)
